User_Auth/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  post 'user/login'
  get 'stickies/index'
  get 'stickies/rout'
  get 'stickies/form'
  post 'stickies/form'

  get 'user/new'
  post 'user/form'

  resources :stickiexs
  resources :user
  root 'welcome#index'

end

User_Auth/app/models/sticky.rb
class Sticky < ActiveRecord::Base
  belongs_to :user
end

User_Auth/app/models/user.rb
class User < ActiveRecord::Base
  has_many :stickies
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create #validating the format of email
  validates :encrypted_password, :presence => true , :confirmation => true, :length => {:in =>2..15} #password_confirmation attr
end

User_Auth/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

User_Auth/app/controllers/stickies_controller.rb
class StickiesController < ApplicationController
  before_action :set_sticky, only: [:show, :edit, :update, :destroy]

  # GET /stickies
  # GET /stickies.json
  def index
    @stickies = Sticky.all
  end

  # GET /stickies/1
  # GET /stickies/1.json
  def show
    # render 'form'
  end

  # GET /stickies/new
  def new
    @sticky = Sticky.new
  end

  # GET /stickies/1/edit
  def edit
    puts 'eeeeeeee'
  end

  # POST /stickies
  # POST /stickies.json
  def form
    @sticky = Sticky.new(sticky_params)
    puts "--------------------------------"
    @sticky['users_id'] = 1;
    puts @sticky.users_id
    puts "------------------------------"+@sticky.title+@sticky.content

    # respond_to do |format|
      if @sticky.save
      #   format.html do
      #     redirect_to @sticky, notice: 'Sticky was successfully created.'
      #   end
      #   format.json { render :show, status: :created, location: @sticky }
        render 'stickies/show'
      else
        render 'stickies_form_path'
        # format.html { render :new }
        # format.json { render json: @sticky.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /stickies/1
  # PATCH/PUT /stickies/1.json
  def update
    respond_to do |format|
      if @sticky.update(sticky_params)
        format.html { redirect_to @sticky, notice: 'Sticky was successfully updated.' }
        format.json { render :show, status: :ok, location: @sticky }
      else
        format.html { render :edit }
        format.json { render json: @sticky.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stickies/1
  # DELETE /stickies/1.json
  def destroy
    @sticky.destroy
    respond_to do |format|
      format.html { redirect_to stickies_url, notice: 'Sticky was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def rout
    render 'form'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sticky
      @sticky = Sticky.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sticky_params
      params.require(:sticky).permit(:title,:users_id, :content)
    end
end

User_Auth/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    render 'user/new'
  end

  def new
    @user = User.new(user_params)
  end

  def show
    render 'login'
  end

  def create
    @user = User.new(user_params)
    logger.info "value of login in param : #{user_params}" #-> log the actual login
    # logger.info "value of login : #{@user.login}"                    #-> log empty
    if @user.save!
      flash[:notice] = "You signed up successfully"
      flash[:color]= "valid"
    else
      flash[:notice] = "Form is invalid"
      flash[:color]= "invalid"
    end
    render 'user/home'
  end

  def user_params
    params.require(:user).permit(:username, :email, :encrypted_password)
  end
  def alert_login_error
    flash[:notice] = "username/password incorect"
    flash[:color]= "invalid"
  end
  def login
    @user = user_params
    @resulted_user = User.find_by_email @user[:email]
    # unless @resulted_user.nil?
    if @resulted_user.nil?
      alert_login_error
      puts '=============================='
      render 'login'
    else
      if (@resulted_user.email.eql? @user[:email]) && (@resulted_user.encrypted_password.eql? @user[:encrypted_password])
        puts @resulted_user.to_s+'------------------'
        session[:user_id] = @resulted_user.id
        render 'home'
      else
        alert_login_error
        render 'login'
      end
    end
  end
end

User_Auth/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

User_Auth/app/helpers/application_helper.rb
module ApplicationHelper
end

User_Auth/app/helpers/authentication_helper.rb
module AuthenticationHelper
end

User_Auth/app/helpers/high_scores_helper.rb
module HighScoresHelper
end

User_Auth/app/helpers/sign_up_helper.rb
module SignUpHelper
end

User_Auth/app/helpers/stickies_helper.rb
module StickiesHelper
end

User_Auth/app/helpers/user_helper.rb
module UserHelper
end

User_Auth/app/helpers/welcome_helper.rb
module WelcomeHelper
end

User_Auth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StickyBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1 class="form_head_div">StickyBoard</h1>
<%= yield %>

</body>
</html>

User_Auth/app/views/stickies/edit.html.erb
<h1>Editing Sticky</h1>

<%= render 'form' %>

<%= link_to 'Show', @sticky %> |
<%= link_to 'Back', stickies_path %>

User_Auth/app/views/stickies/form.html.erb
<%= form_for(:sticky, :url => {:controller => 'stickies', :action => 'form'}) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>


    <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit :create%>
  </div>
<% end %>
<%= link_to 'Back', stickies_index_path %>

User_Auth/app/views/stickies/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New sticky', controller: 'stickies', action: 'rout' %>
<h1>Listing Stickies</h1>

<div class= "sticky_container">
  <% @stickies.each do |sticky| %>
  <div class="sticky">
    <div class="sticky_title">
      <%= sticky.title %>
    </div>
    <div class="sticky_content">
      <%= sticky.content %>
    </div>
  </div>
  <% end %>
</div>

<br>

<!--<%= link_to 'New Sticky',controller: 'stickies'%>-->

User_Auth/app/views/stickies/new.html.erb
<h1>New Sticky</h1>

<%= render 'form' %>

<%= link_to 'Back', stickies_path %>

User_Auth/app/views/stickies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sticky.title %>
</p>


<p>
  <strong>Content:</strong>
  <%= @sticky.content %>
</p>

<%= link_to 'Back', stickies_index_path %>

User_Auth/app/views/user/home.html.erb
<h2>welcome<%=@resulted_user.username%></h2>
<%= link_to 'form', controller: 'stickies', action_name: 'form', render: stickies_form_path%>
<%if @stickies%>
  <div><%@stickies .each do |sticky|%>
  <p><%=sticky.title%></p>
  <% end %></div>
<%end%>

User_Auth/app/views/user/login.html.erb
<div class = "login_container">
  <div class="element_holder">
    <%=form_for(:user,:url =>{:controller => 'user', :action => 'login', :method => 'post'}) do |f|%>
        <h2 class="login_head">login</h2>
        <p><%=f.email_field :email%></p>
        <p><%=f.password_field :encrypted_password%></p>
        <p><%=f.submit :login%></p>
    <% end %>
    don't have acount. <%= link_to 'sign_up', controller: 'user', action: 'create'%>
  </div>
</div>

User_Auth/app/views/user/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form" xmlns="http://www.w3.org/1999/html">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'user', :action => 'create'}) do |f| %>
      <p> Username:</br> <%= f.text_field :username%> </p>
      <p>Email:</br><%=f.text_field :email%></p>
      <p> Password:</br> <%= f.password_field :encrypted_password%></p>
      <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
      <%= f.submit :Signup%>
  <% end %>

</div>

User_Auth/app/views/welcome/index.html.erb
<!--<h1 class="form_head_div">ChatRoom</h1>-->
<div class = "login_container">
  <%= link_to 'login', controller: 'user', action: 'login'%>OR
  <%= link_to 'sign_up', controller: 'user', action: 'form'%>
</div>